# Generated by Django 5.0.7 on 2024-07-30 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('serial_patria', models.IntegerField(blank=True, null=True)),
                ('codigo_patria', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('grado_y_seccion', models.CharField(max_length=12)),
                ('fecha_de_nacimiento', models.DateField()),
                ('lugar_de_nacimiento', models.CharField(max_length=80)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='repreStudy.representante')),
            ],
        ),
    ]
