# Generated by Django 5.0.7 on 2024-07-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0002_rename_reporter_estudiante_representante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representante',
            old_name='Direccion',
            new_name='direccion',
        ),
    ]
