# Generated by Django 5.0.7 on 2024-07-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0003_rename_direccion_representante_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='direccion',
            field=models.TextField(max_length=255),
        ),
    ]
