# Generated by Django 5.0.7 on 2024-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0004_alter_representante_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='lugar_de_nacimiento',
            field=models.TextField(max_length=255),
        ),
    ]
