# Generated by Django 5.0.7 on 2024-07-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0005_alter_estudiante_lugar_de_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
                ('grado_y_seccion', models.CharField(max_length=12)),
                ('fecha_de_nacimiento', models.DateField()),
                ('lugar_de_nacimiento', models.TextField(max_length=255)),
                ('representante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='repreStudy.representante')),
            ],
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
