# Generated by Django 5.0.7 on 2024-07-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0006_alumno_delete_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cedula',
        ),
    ]
