# Generated by Django 5.0.7 on 2024-08-09 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repreStudy', '0007_remove_alumno_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('datos', models.JSONField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
